//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_EF.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblConfirmedOrderlineChange
    {
        public int id { get; set; }
        public int orderId { get; set; }
        public int orderlineId { get; set; }
        public int productlistId { get; set; }
        public string model { get; set; }
        public int customerId { get; set; }
        public string customerName { get; set; }
        public int contactId { get; set; }
        public string contactFullName { get; set; }
        public int promisedQuantity { get; set; }
        public decimal promisedPricePerItem { get; set; }
        public decimal promisedTotal { get; set; }
        public int newQuantity { get; set; }
        public decimal newPricePerItem { get; set; }
        public decimal newTotal { get; set; }
        public string updateStockStatus { get; set; }
        public int updateCount { get; set; }
        public string userRecorded { get; set; }
        public Nullable<int> discrepancy { get; set; }
        public Nullable<System.DateTime> changeDateTime { get; set; }
    
        public virtual TblContact TblContact { get; set; }
        public virtual TblCustomerSupplier TblCustomerSupplier { get; set; }
        public virtual TblOrder TblOrder { get; set; }
        public virtual TblOrderLine TblOrderLine { get; set; }
        public virtual TblProductStock TblProductStock { get; set; }
    }
}
